#!/bin/bash
#
# SessionStart hook for Claude Code on the web.
#
# Brings the repository to a state where `npm run dev`, `npm test` and
# `npm run lint` all work from a cold container: dependencies installed,
# Prisma client generated, Postgres running with migrations applied, and
# enough development data that somebody can actually sign in.
#
# That last part matters more here than in most projects. PRERAAK is
# invite-only by design — a person exists because an admin created them, and
# the Auth.js adapter cannot create one at sign-in. An empty database is
# therefore a locked door with nobody inside, so the preview seeds three
# development accounts.
#
# Idempotent and non-interactive: safe to run on startup, resume and clear.
set -euo pipefail

# Local machines have their own database and environment. Only take over in
# the disposable remote container.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  echo "Not a remote session — leaving the local environment alone."
  exit 0
fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$PROJECT_DIR"

DB_USER="preraak"
DB_PASS="preraak"
DB_HOST="127.0.0.1"
DB_PORT="5432"
DEV_DB="preraak_dev"
TEST_DB="preraak_test"
DEV_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DEV_DB}"
TEST_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${TEST_DB}"

echo "==> Installing dependencies"
# install, not ci: the container image is cached after this hook completes,
# so a warm node_modules is reused on later sessions.
npm install --no-audit --no-fund

echo "==> Generating Prisma client"
npx prisma generate >/dev/null

echo "==> Starting PostgreSQL"
if pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1; then
  echo "    already accepting connections"
elif command -v pg_ctlcluster >/dev/null 2>&1; then
  pg_ctlcluster 16 main start 2>/dev/null || true
  for _ in $(seq 1 30); do
    pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1 && break
    sleep 1
  done
fi

if ! pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1; then
  echo "!!  PostgreSQL did not start. The app and tests need a database;" >&2
  echo "!!  start one and re-run this hook, or set DATABASE_URL yourself." >&2
  exit 1
fi

echo "==> Ensuring role and databases"
su postgres -c "psql -tAc \"SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'\"" | grep -q 1 \
  || su postgres -c "psql -q -c \"CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}' CREATEDB\""

for db in "$DEV_DB" "$TEST_DB"; do
  su postgres -c "psql -tAc \"SELECT 1 FROM pg_database WHERE datname='${db}'\"" | grep -q 1 \
    || su postgres -c "createdb -O ${DB_USER} ${db}"
done

# The app reads .env.local automatically. Never overwrite an existing one —
# it may hold real credentials.
if [ ! -f .env.local ]; then
  echo "==> Writing .env.local (development only, gitignored)"
  cat > .env.local <<ENV
# Generated by .claude/hooks/session-start.sh for this container.
# Development values only. Never commit this file.
DATABASE_URL="${DEV_URL}"
AUTH_SECRET="$(openssl rand -base64 32)"
AUTH_URL="http://localhost:3000"
RESEND_API_KEY=""
EMAIL_FROM="PRERAAK People OS <onboarding@resend.dev>"
ENV
else
  echo "==> .env.local already present, leaving it alone"
fi

if [ ! -f .env.test ]; then
  cat > .env.test <<ENV
DATABASE_URL="${TEST_URL}"
AUTH_SECRET="test-secret-not-for-production-use-only"
AUTH_URL="http://localhost:3000"
RESEND_API_KEY=""
EMAIL_FROM="PRERAAK People OS <test@example.com>"
ENV
fi

echo "==> Applying migrations"
DATABASE_URL="$DEV_URL" npx prisma migrate deploy >/dev/null
DATABASE_URL="$TEST_URL" npx prisma migrate deploy >/dev/null

echo "==> Seeding development data if the database is empty"
PEOPLE=$(PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DEV_DB" \
  -tAc "SELECT count(*) FROM people" 2>/dev/null || echo 0)

if [ "${PEOPLE:-0}" = "0" ]; then
  # The seed script has its own guards: it refuses unless SEED_CONFIRM=DEV,
  # refuses in production, and refuses a non-local DATABASE_URL.
  DATABASE_URL="$DEV_URL" SEED_CONFIRM=DEV npx tsx prisma/seed.ts
else
  echo "    ${PEOPLE} people already present, skipping"
fi

# Make the database reachable from shell commands in this session too.
if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  {
    echo "export DATABASE_URL=\"${DEV_URL}\""
    echo "export TEST_DATABASE_URL=\"${TEST_URL}\""
  } >> "$CLAUDE_ENV_FILE"
fi

cat <<'DONE'

==> Ready.
    npm run dev    the preview serves on port 3000
    npm test       75 tests against preraak_test
    npm run lint   eslint

    Sign in at /login as aditi@dev.local (admin), rohan@dev.local (mentor)
    or meera@dev.local (intern). With no RESEND_API_KEY the sign-in link is
    printed to the dev server's console rather than emailed.
DONE
