#!/usr/bin/env bash
#
# Prepare a working copy so `npm run dev`, `npm test` and `npm run lint` all
# work: dependencies, Prisma client, PostgreSQL, role and databases,
# migrations, a development .env.local, and seed data.
#
# Run it with:  npm run setup
#
# The seeding is not a nicety. PRERAAK is invite-only by construction — a
# person exists because an admin created them, and the Auth.js adapter cannot
# create one at sign-in — so an empty database is a locked door with nobody
# inside and there would be no way to log in at all.
#
# Idempotent and non-interactive. Never overwrites an existing .env.local.
set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$PROJECT_DIR"

DB_USER="${PRERAAK_DB_USER:-preraak}"
DB_PASS="${PRERAAK_DB_PASS:-preraak}"
DB_HOST="${PRERAAK_DB_HOST:-127.0.0.1}"
DB_PORT="${PRERAAK_DB_PORT:-5432}"
DEV_DB="${PRERAAK_DEV_DB:-preraak_dev}"
TEST_DB="${PRERAAK_TEST_DB:-preraak_test}"
DEV_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DEV_DB}"
TEST_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${TEST_DB}"

echo "==> Installing dependencies"
npm install --no-audit --no-fund

echo "==> Generating Prisma client"
npx prisma generate >/dev/null

echo "==> Starting PostgreSQL"
if pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1; then
  echo "    already accepting connections"
elif command -v brew >/dev/null 2>&1; then
  # macOS via Homebrew. The formula is versioned, so start whichever is installed.
  FORMULA="$(brew list --formula 2>/dev/null | grep -E '^postgresql(@[0-9.]+)?$' | head -1 || true)"
  [ -n "$FORMULA" ] && brew services start "$FORMULA" >/dev/null 2>&1 || true
elif command -v pg_ctlcluster >/dev/null 2>&1; then
  # Debian and Ubuntu.
  CLUSTER="$(pg_lsclusters -h 2>/dev/null | awk 'NR==1{print $1" "$2}')"
  [ -n "$CLUSTER" ] && pg_ctlcluster $CLUSTER start 2>/dev/null || true
fi

for _ in $(seq 1 30); do
  pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1 && break
  sleep 1
done

if ! pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1; then
  cat >&2 <<'NOPG'
!!  PostgreSQL is not reachable on this machine, and the app and tests need it.
!!
!!    macOS          brew install postgresql@16 && brew services start postgresql@16
!!    Debian/Ubuntu  sudo apt install postgresql-16 && sudo pg_ctlcluster 16 main start
!!
!!  Already have a database elsewhere? Skip this script, put its connection
!!  string in .env.local as DATABASE_URL, then run:
!!    npx prisma migrate deploy && SEED_CONFIRM=DEV npm run seed
NOPG
  exit 1
fi

# Creating a role needs superuser. Which route works depends on how Postgres
# was installed, so try the usual three rather than assuming a platform.
psql_super() {
  if psql -h "$DB_HOST" -p "$DB_PORT" -d postgres -tAc "$1" 2>/dev/null; then return 0; fi
  if command -v sudo >/dev/null 2>&1 && sudo -n -u postgres psql -tAc "$1" 2>/dev/null; then return 0; fi
  if [ "$(id -u)" = "0" ] && su postgres -c "psql -tAc \"${1//\"/\\\"}\"" 2>/dev/null; then return 0; fi
  return 1
}

echo "==> Ensuring role and databases"
if ! psql_super "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1; then
  psql_super "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}' CREATEDB" >/dev/null \
    || { echo "!!  Could not create the '${DB_USER}' role. Create it yourself:" >&2
         echo "!!    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}' CREATEDB;" >&2; exit 1; }
fi

for db in "$DEV_DB" "$TEST_DB"; do
  if ! psql_super "SELECT 1 FROM pg_database WHERE datname='${db}'" | grep -q 1; then
    psql_super "CREATE DATABASE ${db} OWNER ${DB_USER}" >/dev/null \
      || { echo "!!  Could not create database ${db}." >&2; exit 1; }
  fi
done

# Next.js reads .env.local automatically. Never clobber an existing one; it may
# hold real credentials.
if [ ! -f .env.local ]; then
  echo "==> Writing .env.local (development only, gitignored)"
  SECRET="$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)"
  cat > .env.local <<ENV
# Generated by scripts/setup-local.sh. Development values only.
# Never commit this file.
DATABASE_URL="${DEV_URL}"
AUTH_SECRET="${SECRET}"
AUTH_URL="http://localhost:3000"
RESEND_API_KEY=""
EMAIL_FROM="PRERAAK People OS <onboarding@resend.dev>"
ENV
else
  echo "==> .env.local already present, leaving it alone"
fi

if [ ! -f .env.test ]; then
  cat > .env.test <<ENV
DATABASE_URL="${TEST_URL}"
AUTH_SECRET="test-secret-not-for-production-use-only"
AUTH_URL="http://localhost:3000"
RESEND_API_KEY=""
EMAIL_FROM="PRERAAK People OS <test@example.com>"
ENV
fi

echo "==> Applying migrations"
DATABASE_URL="$DEV_URL" npx prisma migrate deploy >/dev/null
DATABASE_URL="$TEST_URL" npx prisma migrate deploy >/dev/null

echo "==> Seeding development data if the database is empty"
PEOPLE=$(PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DEV_DB" \
  -tAc "SELECT count(*) FROM people" 2>/dev/null || echo 0)

if [ "${PEOPLE:-0}" = "0" ]; then
  # The seed has its own guards: SEED_CONFIRM=DEV, not production, local URL.
  DATABASE_URL="$DEV_URL" SEED_CONFIRM=DEV npx tsx prisma/seed.ts
else
  echo "    ${PEOPLE} people already present, skipping"
fi

cat <<'DONE'

==> Ready.
    npm run dev    http://localhost:3000
    npm test       142 tests
    npm run lint

    Sign in at /login as aditi@dev.local (admin), rohan@dev.local (mentor)
    or meera@dev.local (intern). With no RESEND_API_KEY configured the
    sign-in link is shown on the check-email page and printed to the console.
DONE
